### ISSUE TITLE
Add Istio & kuadrant to local dev workload clusters

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multi-cluster-traffic-controller#29]
## What

Extend the logic for [setting up workload clusters](https://github.com/Kuadrant/multi-cluster-traffic-controller/blob/main/hack/local-setup.sh#L140-L147) to:
- Install the Istio Operator, including the Gateway API CRDs i.e. Gateway, GatewayClass, HttpRoute ...
- Install the Kuadrant Operator, including the Kuadrant API CRDs i.e. AuthPolicy, RateLimitingPolicy, and Authorino & Limitador

## Why
So that a Gateway resource can be created in a local workload cluster.
The intention is for a Gateway to be defined in the control plane, and synced into workload clusters by the traffic controller. This work will be captured in other issues.
This issue is done if a Gateway can be manually created in a workload cluster.

## Links
- [Istio Install docs](https://istio.io/latest/docs/setup/install/)
- [Kuadrant Operator](https://github.com/Kuadrant/kuadrant-operator)
- [Kuadrant Slack](https://kuadrant.slack.com/archives/C02NBERKR0R)

**Comment by sergioifg94** [comment]
### A note on Istio and Gateway API

By default Istio supports the Gateway API but does not include it. In order to install the Gateway API CRDs, it can be done with:
```sh
kustomize build "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.6.0" | kubectl apply -f
```

More info on it:
* https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/
* https://istio.io/latest/docs/setup/additional-setup/getting-started/

**Comment by sergioifg94** [comment]
Completed after merging #61 and #37
